server:
  port: 9090
  servlet:
    context-path: /
logging:
  file:
    name: logs/log.log
spring:
  thymeleaf:
    cache: false #开发时关闭缓存，不然没法看到实时画面
    mode: LEGACYHTML5 #用非严格的HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?userUnicode=true&characterEncoding=utf-8&userSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.example.hellospringboot.entity #实体类存放的路径
  mapper-locations: classpath:mapper/*.xml